### ISSUE TITLE
Tools - WoW Injector

### ISSUE THREAD

**Issue by Nexvelius** [Multi-Emu/Project-WoW#1]
Hello.
Please tell me where I can obtain the latest version of the WoW(wod)-Injector?

**Comment by Fabi** [comment]
Will add it later today maybe..

**Comment by Nexvelius** [comment]
Thanks, we will wait.

**Comment by Extred** [comment]
Hello again.
What about "awpp"? There are only empty awpp projects in forked Arctium reps. Or is it not yet implemented?
Also, is it possible to work with awps dumps using TrinityCore's WowPacketParser?

**Comment by Fabi** [comment]
You can implement your own parser class in wpp
